### ISSUE TITLE
about files in typescript/src/languages/

### ISSUE THREAD

**Issue by leowang7553** [rodrigopivi/aida#9]
Hi, I am a web developer, I learn NLP with your aida. I got a question that where are the files in typescript/src/languages come from?

thanks very much!

**Comment by rodrigopivi** [comment]
> Hi, I am a web developer, I learn NLP with your aida. I got a question that where are the files in typescript/src/languages come from?
> 
> thanks very much!

Hi, those are fastText embeddings.
